config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/wait', to: 'home#wait'

  resources :sessions
  resources :users
  resources :castings do
    member do
      get :join
      get :apply
      post :kick
      post :interview
      post :register
      get 'private/:private_id', action: 'private'
    end
  end
  post 'pusher/auth', to: 'pusher#auth'
  post 'pusher/channel', to: 'pusher#channel'
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  belongs_to :casting
end

app/models/casting.rb
class Casting < ActiveRecord::Base
  belongs_to :user
  has_many :applicants

  def fetch_interview
    self.interview ||= "interview_#{SecureRandom.uuid[0,5]}"
  end

  def channel
    "castings_#{id}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :castings

  enum kind: { user: 0, admin: 1 }

  has_secure_password

  validates :password, :length => { :minimum => 6 },
            :on => :create

  validates :password, :length => { :minimum => 6 },
            :on => :update,
            :if => :password_digest_changed?

  validates_uniqueness_of :email, :case_sensitive => false, :message => 'is in use.'
  validates_presence_of   :email

  before_create { generate_token(:auth_token) }
  before_create { generate_token(:confirmation_token) }

  def confirm
    self.touch(:confirmed_at)
  end

  def confirmed?
    !!self.confirmed_at
  end

  def generate_token(column)
    self[column] = unique_token_for(column)
  end

  def unique_token_for(column)
    begin
      token = SecureRandom.urlsafe_base64
    end while User.exists?(column => token)
    token
  end

  def send_password_reset_email
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    self.save!
    UserMailer.password_reset(self.id).deliver
  end

  def send_confirmation_email
    UserMailer.email_confirmation(self.id).deliver
  end
end

app/controllers/application_controller.rb
include WoopraRailsSDK

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :signed_in?, :current_user

  before_filter :woopra, :current_user

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end

  def signed_in?
    true if current_user
  end

  def authorize
    unless signed_in?
      respond_to do |format|
        format.html { redirect_to new_session_path, :alert => 'Please sign in to continue.' }
      end
    end
  end

  def woopra
    woopra = WoopraTracker.new(request)
    @woopra_code = woopra.js_code
    woopra.config({ domain: 'casthire.com' })
    woopra.identify({ email: current_user.email }).track if current_user
    woopra.set_woopra_cookie(cookies)
    woopra
  end
end

app/controllers/castings_controller.rb
class CastingsController < ApplicationController
  include ActionController::Live
  before_filter :authorize, except: [:apply, :private, :register, :wait]
  before_filter :authorize_creator, only: :show

  def index
    woopra.track 'viewed casting list', {}, true
    @castings = Casting.where(user: current_user)
    @casting = Casting.new
    gon.casting = @casting
  end

  def create
    woopra.track 'created casting ' + params[:casting][:name].to_s, {}, true
    casting = Casting.new(casting_params)
    casting.user = current_user
    casting.save
    redirect_to castings_path
  end

  def show
    woopra.track 'joined admin casting page ' + @casting.name.to_s, {}, true
    gon.casting = @casting
    gon.pusher_key = Pusher.key
    session[:username] = "Host"
    gon.username = "Host" #todo: use a name from the users profile.
  end

  def apply
    gon.username = session[:username] if session[:username]
    @casting = Casting.find(params[:id])
    woopra.track 'join casting page ' + @casting.name.to_s, {}, true
    @applicant = Applicant.new(params[:applicant])
    @applicant.casting = @casting
    @applicant.save
    gon.casting = @casting
    gon.pusher_key = Pusher.key
  end

  def kick
    @casting = Casting.find(params[:id])

    Pusher["presence-casthire_#{@casting.id}"].trigger('kick', {
        :peer => params[:peer]
    })
    render json: true
  end

  def interview
    @casting = Casting.find(params[:id])
    @casting.started_interview = Time.now
    interview = @casting.fetch_interview
    @casting.save

    Pusher["presence-casthire_#{@casting.id}"].trigger('interview', {
        :peers => params[:peers],
        :interview => interview,
        :time => @casting.started_interview
    })

    render json: { interview: interview }
  end

  def register
    session[:peer] = params[:peer]
    puts "setting session username to #{params[:username]}"
    session[:username] = params[:username]
    render json: { peer: session[:peer] }
  end

  def private
    @casting = Casting.find(params[:id])
    gon.private_id = params[:private_id]
    gon.casting = @casting
    gon.pusher_key = Pusher.key
    puts "setting session: #{session[:username]}"
    gon.username = session[:username] if !!session[:username]

    @back_path = @casting.user == current_user ? casting_path(@casting) : apply_casting_path(@casting)
  end

  def update
    woopra.track 'updated casting', {}, true
    Casting.update(params[:id], casting_params)
    redirect_to casting_path(params[:id])
  end

  def destroy
    woopra.track 'deleted casting', {}, true
    Casting.destroy(params[:id])
    flash[:success] = 'Successfully deleted Casting'
    redirect_to castings_path
  end

  private

  def authorize_creator
    @casting = Casting.find(params[:id])
    unless @casting.user == current_user
      redirect_to apply
    end
  end

  def casting_params
    params.require(:casting).permit(:name)
  end

  def applicant_params
    params.require(:applicant).permit(:name)
  end

  def sse(object, options = {})
    (options.map{|k,v| "#{k}: #{v}" } << "data: #{object.to_json}").join("\n") + "\n\n"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to castings_path if signed_in?
  end
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
  protect_from_forgery :except => [:auth, :channel] # stop rails CSRF protection for this action

  def auth
    response = Pusher[params[:channel_name]].authenticate(params[:socket_id], {
      user_id: session[:username],
      user_info: {
        name: session[:username],
        peer: session[:peer]
      }
    })
    render :json => response
  end

  def channel
    webhook = Pusher::WebHook.new(request)
    if webhook.valid?
      webhook.events.each do |event|
        #todo: more webhook work
        if event['name'] == 'channel_vacated'
          id = event['channel'].gsub('presence-','')
          casting = Casting.where(interview: id).first
          if (casting)
            casting.started_interview = nil
            casting.interview = nil
            casting.save

            Pusher["presence-casthire_#{casting.id}"].trigger('stop_interview', {})
          end
        end
      end
      render json: true
    else
      render 401
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]

  def new
    woopra.track 'visited login page', {}, true
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      woopra.track 'logged in', {}, true
      cookies.permanent[:auth_token] = user.auth_token
      redirect_to root_path
    else
      woopra.track 'failed login', {}, true
      flash[:error] = 'Invalid email or password.'
      redirect_to new_session_path
    end
  end

  def destroy
    woopra.track 'logged out', {}, true
    cookies.delete(:auth_token)

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize

  def new
    woopra.track 'visted new user page', {}, true
    @user = User.new

    respond_to do |format|
      format.html
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      woopra.track 'created user', {}, true
      cookies.permanent[:auth_token] = @user.auth_token
      redirect_to root_path
    else
      woopra.track 'failed creating user', {}, true
      flash[:error] = 'Something went wrong. Please try again.'
      render action: 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casting_helper.rb
module CastingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/castings/_ended.html.haml
#ended.notice
  Your interview has ended

app/views/castings/_group.html.haml
.group.shadow
  %h3#group-title.group-title
    %span#group-indicator.fa.fa-caret-right
    Group Interview
  #group-details
    %ul#group-list.group-list

    %a#group-interview.btn.extra-spacing-vertical Start Interview

app/views/castings/_inputs.html.haml
#inputs
  #selectDevices.btn-control.tooltip-trigger
    .tooltip-right
      .tooltip-arrow-right
      .tooltip-inner
        Switch camera
    = image_tag('ic_switch_video_white_24dp.png', class: 'btn-control-icon')
  #devicePicker
    %a#btn-close.fa.fa-times
    #videoInput
      %label{for: 'videoSource'} Camera:
      %select#videoSource
        %option Default
    #audioInput
      %label{for: 'audioSource'} Microphone:
      %select#audioSource

app/views/castings/_main.html.haml
#controls.controls
  %a#mute.btn-control.tooltip-trigger
    .tooltip-right
      .tooltip-arrow-right
      .tooltip-inner
        Mute
    = image_tag('ic_mic_none_white_24dp.png', class: 'btn-control-icon')
  %a#unmute.btn-control-off.tooltip-trigger
    .tooltip-right
      .tooltip-arrow-right
      .tooltip-inner
        Unmute
    = image_tag('ic_mic_off_white_24dp.png', class: 'btn-control-icon')
  %a#muteVideo.btn-control.tooltip-trigger
    .tooltip-right
      .tooltip-arrow-right
      .tooltip-inner
        Turn off video
    = image_tag('ic_videocam_white_24dp.png', class: 'btn-control-icon')
  %a#unmuteVideo.btn-control-off.tooltip-trigger
    .tooltip-right
      .tooltip-arrow-right
      .tooltip-inner
        Turn on video
    = image_tag('ic_videocam_off_white_24dp.png', class: 'btn-control-icon')
  = render 'inputs'

#main
  #videoBar
    #local
      .video-container.clearfix
        %video#localVideo
    #remoteVideos
  .names

#timer

- if signed_in? && current_page?(casting_path)
  = render 'group'

app/views/castings/_name.html.haml
#nameBox.highlight-box.text-center
  %form.form-inline#nameForm{:role => 'form'}
    %label.big-label.sr-only{:for => 'name'} What's your name?
    %input#name.form-control{:placeholder => 'Enter your name', :type => 'text'}/
    %button.btn.btn-full-width{:type => 'submit'} Go

app/views/castings/_permissions.html.haml
- if current_page?(apply_casting_path)
  #permissions.alert-inline
    Welcome to the interview! To begin, please do the following:
    %ol
      %li Enter your name above.
      %li
        Press
        %strong "Allow"
        or
        %strong "Share"
        at the top of this window to allow access to your camera and microphone, if you have not already done so.
- elsif current_page?(casting_path)
  #permissions.hero-section.text-center
    .container
      .highlight-box
        Please wait while the Casting Call begins. Make sure you have allowed access to your camera and microphone.

app/views/castings/_unsupported.html.haml
#unsupported
  .alert
    Your browser is currently not supported
    %span.fa.fa-frown-o
    \. Please download the latest Chrome or Firefox.

app/views/castings/apply.html.haml
= javascript_include_tag 'webrtc'

= render 'unsupported'

%section.hero-section
  .container
    = render 'name'
    = render 'permissions'

= render 'main'
= render 'ended'

app/views/castings/index.html.haml
%section
  .left-box.box.box-white
    %h2.underline-header Casting Calls
    %table
      %thead
        %tr
          %th Name
          %th Link
          %th.narrow Actions
      %tbody
        - @castings.each do |casting|
          %tr
            %td= casting.name
            %td
              .copy
                %input.casting-link{id: "casting-link-#{casting.id}", value: "#{apply_casting_url(casting.id)}"}
                %button.casting-clip.btn.btn-sm{id: "casting-clip-#{casting.id}", 'data-clipboard-target' => "casting-link-#{casting.id}", :title => 'Click me to copy to clipboard.'}
                  %span.fa.fa-clipboard
                .tooltip{id: "tooltip-#{casting.id}"}
                  .tooltip-arrow
                  .tooltip-inner
                    Copied!
            %td.narrow
              = link_to casting_path(casting), class: 'btn' do
                %span.fa.fa-video-camera
                Start Casting Call
              = link_to casting_path(casting), method: :delete, data: { confirm: 'Are you sure you want to delete this casting?' }, class: 'btn btn-danger' do
                %span.fa.fa-times
                Delete Casting
              :javascript
                $(document).ready(function() {
                  if (FlashDetect.installed) {
                    var clip = new ZeroClipboard($('#casting-clip-#{casting.id}'));
                    clip.on('aftercopy', function(event) {
                      // Display "Copied!" tooltip
                      $('#tooltip-#{casting.id}').css('display', 'inline-block');
                      setTimeout(function() {
                        $('#tooltip-#{casting.id}').css('display', 'none');
                      }, 1000)
                    })
                  } else {
                    $('body').append('<div class="alert">Please install and/or enable Flash to use the copy button: <a href="http://get.adobe.com/flashplayer/">Get Adobe Flash Player</a></div>')
                  }
                });

app/views/castings/private.html.haml
= javascript_include_tag 'webrtc'

= render 'unsupported'
= render 'permissions'

#interview.notice
  You are currently in an interview room.
  %span#interview-info
  = link_to 'Back to the Lobby', @back_path, :class => 'btn btn-xs'

#loading.hero-section.text-center
  .container
    .highlight-box
      %h2 Hi there! Please sit tight while we wait for more people to join the interview.
      = image_tag('loading.gif', class: 'loading-icon')

= render 'main'

app/views/castings/show.html.haml
= javascript_include_tag 'webrtc'

= render 'unsupported'
= render 'permissions'

#share.notice
  Casting Call is ready! Share this link:
  .copy
    %input#casting-link.casting-link{value: "#{apply_casting_url(@casting.id)}"}
    %button.casting-clip.btn.btn-sm{'data-clipboard-target' => 'casting-link', :title => 'Click me to copy to clipboard.'}
      %span.fa.fa-clipboard
    .tooltip
      .tooltip-arrow
      .tooltip-inner
        Copied!

= render 'main'

:javascript
  $(document).ready(function() {
    if (FlashDetect.installed) {
      var clip = new ZeroClipboard($('.casting-clip'));
      clip.on('aftercopy', function(event) {
        // Display "Copied!" tooltip
        $('.tooltip').css('display', 'inline-block');
        setTimeout(function() {
          $('.tooltip').css('display', 'none');
        }, 1000)
      })
    } else {
      $('body').append('<div class="alert">Please install and/or enable Flash to use the copy button: <a href="http://get.adobe.com/flashplayer/">Get Adobe Flash Player</a></div>')
    }
  });

app/views/home/index.html.haml
%section#hero-section-office.hero-section.text-center
  .container
    .highlight-box
      %h1 CastHire
      %h2
      %p
        CastHire is just like your regular Casting Call, but digitized. Invite all your potential hires into your digital "lobby."

        Address all of your candidates at once.
        When you're ready, bring them in one by one or in groups to a private interview room.
        While in the interview, your candidates in the lobby won't be able to see or hear you (though they will be able to talk to each other).
        After you're finished interviewing your candidate, click 'back to lobby.' CastHire is a more personal but more efficient means to screen your candidates.
        Best of all, CastHire will be a FREE to use platform during our beta. To sign up, go to http://casthire.com/users/new.
        Please note, CastHire requires Chrome or Firefox.
      %p
        = link_to 'Sign in', new_session_path, class: 'btn btn-primary btn-lg extra-spacing-vertical'

  .transparent-bar-dark.footer-highlight
    %ul#contact-list
      %li.contact-list-item
        %span.footer-icon.fa.fa-phone-square
        (818) 583-7080
      %li.contact-list-item
        %a{href: 'mailto:support@casthire.com'}
          %span.footer-icon.fa.fa-envelope
          support@casthire.com

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title CastHire
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css', media: 'all'
    = include_gon
    = @woopra_code
    :javascript
      woopra.config({domain: 'casthire.com'})
    :javascript
      woopra.track()
    = javascript_include_tag 'application'
    = javascript_include_tag 'https://js.pusher.com/2.0/pusher.min.js'
    = csrf_meta_tags
  %body
    %nav#navigation{role: 'navigation'}
      .container-fluid
        .row
          .navbar-header.col2
            %a.navbar-brand.link-on-dark{href: '/'} CastHire
          - if !signed_in? && @casting == nil
            .navbar-collapse.col9.right
              %ul.navbar-nav
                // %li
                //   = link_to 'Explore', new_user_path, :class => 'link-on-dark'
                // %li
                //   = link_to 'Pricing', new_user_path, :class => 'link-on-dark'
                // %li
                //   = link_to 'Try It Free', new_user_path, :class => 'link-on-dark'
                // %li
                //   = link_to 'Support', new_user_path, :class => 'link-on-dark'
                %li
                  = link_to 'Sign In', new_session_path, :class => 'link-on-dark'

    %div{class: "controller_#{params[:controller].gsub("/","_")} action_#{params[:action]}"}
      - flash.each do |name, msg|
        %div{class: "alert alert-#{name}"}
          = msg

      = yield

    - if signed_in?
      = render 'shared/sidebar'

app/views/shared/_sidebar.html.haml
- if current_page?(castings_path)
  .right-box.box
    %h4 Create a Casting Call
    = form_for @casting, role: 'form' do |f|
      .form-group
        = f.text_field :name, placeholder: 'Enter Name', class: 'form-control'
        = f.submit class: 'btn btn-center'

  .corner
    = link_to 'Sign out', session_path(1), method: :delete, :class => 'btn'

app/views/users/new.html.haml
%section#hero-section-desk.hero-section.text-center
  .container
    = form_for @user, :url => users_path, :html => { :class => 'highlight-box', :id => 'user-form' } do |f|
      %h2 Sign Up
      - if @user.errors.any?
        .errors
          %p There were problems with your registration.
          %ul
            - @user.errors.full_messages.each do |message|
              %li
                = message
      %p
        = f.text_field :email, placeholder: 'email'
      %p
        = f.password_field :password, placeholder: 'password'
      %p
        = f.password_field :password_confirmation, placeholder: 'confirm password'
      = f.submit 'Sign Up', class: 'btn extra-spacing-vertical'
      %p.text-center
        = link_to 'Already have an account?', new_session_path